site_name: Riichi Book
docs_dir: docs
site_dir: site
site_url: https://example.com
theme:
  name: material
  font:
    text: Noto Sans JP
    code: Red Hat Mono
  logo: assets/chun.png
  favicon: assets/chun.png
  features:
    - navigation.footer
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.sections
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra:
  alternate:
    - name: English
      link: /English/
      lang: en
    - name: Indonesia
      link: /Indonesia/
      lang: id      
    - name: 日本語
      link: /Japanese/
      lang: ja

  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@james-willett
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/willettjames/

plugins:
  - glightbox

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - Home: index.md
  - English:
    - About:
      - English/00_About/01_Introduction.md
      - English/00_About/02_Credit.md
      - English/00_About/03_Preface.md
      - English/00_About/04_Plan_of_the_book.md
      - English/00_About/05_Daftar_Isi.md
    - Chapter 1 - Introduction to Tenhou:
      - English/01_Introduction_to_Tenhou/01_Why_play_online.md
      - English/01_Introduction_to_Tenhou/02_Setting_up_an_account.md
      - English/01_Introduction_to_Tenhou/03_The_main_page.md
      - English/01_Introduction_to_Tenhou/04_Playing_a_game.md
      - English/01_Introduction_to_Tenhou/05_Troubleshooting.md
      - English/01_Introduction_to_Tenhou/06_Rules.md
    - Chapter 2 - Advanced Features of Tenhou:
      - English/02_Advanced_features_of_Tenhou/01_Rank_and_rating.md
      - English/02_Advanced_features_of_Tenhou/02_Four_rooms.md
      - English/02_Advanced_features_of_Tenhou/03_Reading_the_statistics.md
      - English/02_Advanced_features_of_Tenhou/04_Viewing_games.md
    - Chapter 3 - Riichi Mahjong Basics:
      - English/03_Riichi_mahjong_basics/01_Learning_strategies.md
      - English/03_Riichi_mahjong_basics/02_Basic_building_blocks.md
      - English/03_Riichi_mahjong_basics/03_Complex_shapes.md
      - English/03_Riichi_mahjong_basics/04_Waits.md
      - English/03_Riichi_mahjong_basics/05_Glossary.md
    - Chapter 4 - The Five Block Method:
      - English/04_The_ﬁve-block_method/00_The_five_block_method.md
      - English/04_The_ﬁve-block_method/01_Finding_a_redundant_tile.md
      - English/04_The_ﬁve-block_method/02_Alternative_conﬁgurations.md
      - English/04_The_ﬁve-block_method/03_Selecting_tile_blocks.md
      - English/04_The_ﬁve-block_method/04_Building_a_block.md
  - Indonesia:
    - Home: /Indonesia/
  - Japanese:
    - Home: /Japanese/